#!/bin/bash
mkdir -p "data"

for url in $(curl -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/search/code?q=filename:.env%20language:shell&per_page=100&sort=indexed" | jq -r '.items | .[] | .html_url'); do
  ./process-search-result "$url"
done
