#!/bin/bash
mkdir -p "data"

for i in {1..100}; do 
  echo "Page: $i"
  for url in $(curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/search/code?q=key%20filename:.env%20language:shell&per_page=100&page=$i" | jq -r '.items | .[] | .html_url'); do
    ./process-search-result "$url"
  done
  sleep 60
done
