name: Generate report
on:
  workflow_dispatch:
  schedule:
    - cron: '5 6 * * *' # Once per day in the morning

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Checkout scripts
        uses: actions/checkout@v3

      - name: Move bin
        run: mv ./bin/* /usr/local/bin/

      - name: Checkout data
        uses: actions/checkout@v3
        with:
          ref: data

      - name: Generate report
        run: |
          generate-report dotenv
          generate-report actions

      - name: Commit result
        env:
          DIR: reports
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ $(git status --porcelain $DIR) ]]; then
            git pull
            git add $DIR
            git commit -m "Generate report"
            git push
          fi
