name: Generate report
on:
  workflow_dispatch:
  schedule:
    - cron: '5 6 * * *' # Once per day in the morning

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: data

      - name: Generate report
        run: ./generate-report

      - name: Commit result
        env:
          FILE: report.csv
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ $(git status --porcelain $FILE) ]]; then
            git add $FILE
            git commit -m "Generate report"
            git push
          fi
