name: Run
on:
  workflow_dispatch:
  schedule:
    - cron: '1/15 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: data

      - name: Run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./search-dotenv

      - name: Commit result
        env:
          DIR: data
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ $(git status --porcelain $DIR) ]]; then
            git add $DIR
            git commit -m "Add search results"
            git push
          fi
